<?php

declare(strict_types=1);

if ($method !== 'POST') {
    json_err('Method not allowed.', 405);
}

$body       = api_body();
$cidr_input = trim((string)($body['cidr']       ?? ''));
$ns_raw     = trim((string)($body['ns']         ?? 'ns1.example.com.'));
$hm_raw     = trim((string)($body['hostmaster'] ?? 'hostmaster.example.com.'));
$ttl        = (int)($body['ttl'] ?? 86400);
$serial_raw = trim((string)($body['serial']     ?? ''));
$domain_raw = trim((string)($body['domain']     ?? 'example.com'));

if ($cidr_input === '') {
    json_err('Field "cidr" is required.');
}
if ($ns_raw === '') {
    json_err('Field "ns" must not be empty.');
}
if ($ttl < 60 || $ttl > 2147483647) {
    json_err('Field "ttl" must be between 60 and 2147483647.');
}

// Normalise FQDN fields: ensure trailing dot
$ns     = rtrim($ns_raw, '.') . '.';
$hm     = rtrim($hm_raw, '.') . '.';
$domain = rtrim($domain_raw, '.');

// Generate SOA serial: default to YYYYMMDDnn
if ($serial_raw === '') {
    $serial = (int)(date('Ymd') . '01');
} else {
    $serial = (int)$serial_raw;
    if ($serial <= 0) {
        json_err('Field "serial" must be a positive integer.');
    }
}

// ── Dispatch on IP version ────────────────────────────────────────────────────
if (str_contains($cidr_input, ':')) {
    // ── IPv6 path ─────────────────────────────────────────────────────────────
    if (!extension_loaded('gmp')) {
        json_err('IPv6 requires the PHP GMP extension.', 500);
    }

    $r = resolve_ipv6_input($cidr_input, '');
    if (!$r['result6']) {
        json_err($r['error6'] ?? 'Invalid IPv6 CIDR.');
    }

    /** @var array<string,mixed> $result6 */
    $result6 = $r['result6'];
    $prefix  = (int)ltrim((string)$result6['prefix'], '/');

    if ($prefix < 112) {
        json_err('IPv6 subnet too large. Prefix must be /112 or greater (max 65 536 addresses).');
    }

    $zone      = (string)$result6['ptr_zone'];
    $host_bits = 128 - $prefix;
    $total     = (int)gmp_strval(gmp_pow(2, $host_bits));
    $net_gmp   = ipv6_to_gmp((string)$result6['first_ip']);
    $zone_sfx  = '.' . $zone;

    $lines = [
        '; Zone file for ' . $zone,
        '; Generated by Subnet Calculator',
        ';',
        '$ORIGIN ' . $zone . '.',
        '$TTL ' . $ttl,
        '@  IN  SOA  ' . $ns . '  ' . $hm . ' (',
        '           ' . $serial . ' ; serial',
        '           3600        ; refresh',
        '           900         ; retry',
        '           604800      ; expire',
        '           300 )       ; minimum TTL',
        '   IN  NS  ' . $ns,
        '',
        '; PTR records (' . $total . ' addresses)',
    ];

    for ($i = 0; $i < $total; $i++) {
        $ip_gmp  = gmp_add($net_gmp, gmp_init($i));
        $ip      = gmp_to_ipv6($ip_gmp);
        $raw_bin = inet_pton($ip);
        if ($raw_bin === false) {
            continue;
        }
        $hex      = bin2hex($raw_bin);
        $nibbles  = str_split($hex);
        $full_rev = implode('.', array_reverse($nibbles)) . '.ip6.arpa';
        $owner    = str_ends_with($full_rev, $zone_sfx)
            ? substr($full_rev, 0, strlen($full_rev) - strlen($zone_sfx))
            : $full_rev;
        $hostname = str_replace(':', '-', $ip) . '.' . $domain . '.';
        $lines[]  = $owner . '  IN  PTR  ' . $hostname;
    }

    json_ok([
        'zone'         => $zone,
        'format'       => 'bind',
        'ttl'          => $ttl,
        'record_count' => $total,
        'content'      => implode("\n", $lines),
    ]);
} else {
    // ── IPv4 path ─────────────────────────────────────────────────────────────
    $r = resolve_ipv4_input($cidr_input, '');
    if (!$r['result']) {
        json_err($r['error'] ?? 'Invalid IPv4 CIDR.');
    }

    /** @var array<string,mixed> $result */
    $result       = $r['result'];
    $network_cidr = (string)$result['network_cidr'];
    $prefix       = (int)ltrim((string)$result['netmask_cidr'], '/');

    if ($prefix < 16) {
        json_err('IPv4 subnet too large. Prefix must be /16 or greater (max 65 536 addresses).');
    }

    $zone     = (string)$result['ptr_zone'];
    $total    = 1 << (32 - $prefix);  // safe: prefix >= 16, so shift <= 16
    $zone_sfx = '.' . $zone;

    [$network_ip] = explode('/', $network_cidr);
    $ip_long = ip2long($network_ip);
    if ($ip_long === false) {
        json_err('Internal error resolving network address.', 500);
    }
    $net_long = $ip_long & 0xFFFFFFFF;

    $lines = [
        '; Zone file for ' . $zone,
        '; Generated by Subnet Calculator',
        ';',
        '$ORIGIN ' . $zone . '.',
        '$TTL ' . $ttl,
        '@  IN  SOA  ' . $ns . '  ' . $hm . ' (',
        '           ' . $serial . ' ; serial',
        '           3600        ; refresh',
        '           900         ; retry',
        '           604800      ; expire',
        '           300 )       ; minimum TTL',
        '   IN  NS  ' . $ns,
        '',
        '; PTR records (' . $total . ' addresses)',
    ];

    for ($i = 0; $i < $total; $i++) {
        $ip  = long2ip(($net_long + $i) & 0xFFFFFFFF);
        $o   = explode('.', $ip);
        // Full reverse-DNS name for this IP
        $full_rev = "{$o[3]}.{$o[2]}.{$o[1]}.{$o[0]}.in-addr.arpa";
        $owner    = str_ends_with($full_rev, $zone_sfx)
            ? substr($full_rev, 0, strlen($full_rev) - strlen($zone_sfx))
            : $full_rev;
        $hostname = str_replace('.', '-', $ip) . '.' . $domain . '.';
        $lines[]  = $owner . '  IN  PTR  ' . $hostname;
    }

    json_ok([
        'zone'         => $zone,
        'format'       => 'bind',
        'ttl'          => $ttl,
        'record_count' => $total,
        'content'      => implode("\n", $lines),
    ]);
}
